spring:
  application:
    name: web-application

server:
  port: 6464

ribbon:
  http:
    client:
      enabled: true

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true